### PR TITLE
Updated to output correct PART numbers up to TEN

### PR DESCRIPTION
**Pull request by kabutz**

### CODE REVIEW

**Comment by mraible** [comment]
Hmmmm, I don't see any changes. 🤔

**Comment by kabutz** [comment]
That's odd - perhaps because you changed your branch names from master to main?

**Comment by kabutz** [comment]
https://github.com/mraible/infoq-mini-book/pull/59/commits/970ccba8490bf0760ae59d3e5309e85614ad41e4 - I changed the output to correct the PART numbers up to TEN

**Comment by mraible** [comment]
Yeah, I can see your first commit with the changes. However, this PR says "Files changed 0".

**Pull request closed without merging**
