### PR TITLE
Upgrade dependencies to latest versions

### PR DESCRIPTION
**Pull request by mraible**
This seems to generate HTML, EPUB, and PDF just fine, but fails for MOBI.

```
$ ./gradlew

...

> Task :mobi
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/Users/mraible/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy/2.4.15/74b7e0b99526c569e3a59cb84dbcc6204d601ee6/groovy-2.4.15.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Jun 25, 2020 12:55:12 PM uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/parser.rb next_section
SEVERE: chapters/preface.adoc: line 1: invalid part, must have at least one section (e.g., chapter, appendix, etc.)
Jun 25, 2020 12:55:13 PM uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/parser.rb next_section
SEVERE: index.adoc: line 41: invalid part, must have at least one section (e.g., chapter, appendix, etc.)
Jun 25, 2020 12:55:13 PM uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/parser.rb next_section
SEVERE: index.adoc: line 43: invalid part, must have at least one section (e.g., chapter, appendix, etc.)
Jun 25, 2020 12:55:13 PM uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/parser.rb next_section
SEVERE: index.adoc: line 45: invalid part, must have at least one section (e.g., chapter, appendix, etc.)
Jun 25, 2020 12:55:13 PM uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/parser.rb next_section
SEVERE: chapters/action.adoc: line 2: invalid part, must have at least one section (e.g., chapter, appendix, etc.)
Jun 25, 2020 12:55:13 PM uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/parser.rb next_section
SEVERE: index.adoc: line 55: invalid part, must have at least one section (e.g., chapter, appendix, etc.)
Jun 25, 2020 12:55:14 PM uri:classloader:/gems/asciidoctor-epub3-1.5.0.alpha.16/lib/asciidoctor-epub3/converter.rb distill_epub_to_mobi
INFO: sh: kindlegen: command not found
Jun 25, 2020 12:55:14 PM uri:classloader:/gems/asciidoctor-epub3-1.5.0.alpha.16/lib/asciidoctor-epub3/converter.rb write
SEVERE: KindleGen failed to write MOBI to /Users/mraible/dev/infoq-mini-book/build/asciidoc/epub3/index.mobi
```

Any ideas @mojavelinux @wimdeblauwe?

### CODE REVIEW

**Comment by mojavelinux** [comment]
There have been some changes in asciidoctor-epub3 with how the kindlegen binary is located. I don't work on that project anymore, so I would direct your inquire to the project itself.

We also need a 1.5.0-alpha.17 release of asciidoctorj-epub3 since alpha.16 is not the latest release.

**Comment by mraible** [comment]
@mojavelinux FWIW, I created a [PR to add CI](https://github.com/mraible/infoq-mini-book/pull/31) to this project and it happens with the current versions too.

**Comment by mraible** [comment]
It looks like it works on Ubuntu and fails on Mac and Windows. [Failure on Mac](https://github.com/mraible/infoq-mini-book/pull/31/checks?check_run_id=808678839#step:4:144) is:

```
sh: /Users/runner/work/infoq-mini-book/infoq-mini-book/build/kindlegen/kindlegen: Bad CPU type in executable
```

I need to fix the build so that reports as a failure. It currently says it succeeds. 

[Windows failure](https://github.com/mraible/infoq-mini-book/pull/31/checks?check_run_id=808678863#step:4:144):

```
SEVERE: (ENOENT) No such file or directory - D:/a/infoq-mini-book/infoq-mini-book/build/kindlegen/kindlegen -
  dont_append_source -c0 -o index.mobi D:/a/infoq-mini-book/infoq-mini-book/build/asciidoc/epub3/index-kf8.epub
##[error]Exception in thread "main" org.asciidoctor.gradle.backported.AsciidoctorRemoteExecutionException: 
  Error running Asciidoctor whilst attempting to process D:\a\infoq-mini-book\infoq-mini-book\src\docs\asciidoc\index.adoc using backend epub3
	at org.asciidoctor.gradle.backported.AsciidoctorJavaExec$_convertFiles_closure3.doCall(AsciidoctorJavaExec.groovy:63)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.Closure.call(Closure.java:418)
	at groovy.lang.Closure.call(Closure.java:434)
```

**Comment by wimdeblauwe** [comment]
> Bad CPU type in executable

What macOS version are you using? If it is Catalina, it probably means that you have a 32-bit executable, which no longer is possible to run on macOS Catalina.

**Comment by mraible** [comment]
@wimdeblauwe I'm using macOS Catalina v10.15.5. Are you saying that I can no longer build a MOBI file because of my OS?

**Comment by wimdeblauwe** [comment]
@mraible Catalina no longer allows to run 32-bit executables. I just had a look to your branch, and it is indeed a 32-bit executable:

```
wdb@Wims-MBP kindlegen % file kindlegen
kindlegen: Mach-O executable i386
```

You can also see in the download URL that the build downloads a 32-bit version: https://github.com/mraible/infoq-mini-book/blob/master/build.gradle#L85

```
src OperatingSystem.current().isMacOsX() ? 'https://kindlegen.s3.amazonaws.com/KindleGen_Mac_i386_v2_9.zip' : 'http://kindlegen.s3.amazonaws.com/kindlegen_linux_2.6_i386_v2_9.tar.gz'
```

I did not find a new download link for the 64-bit version. Only a forum post that points that claims that Kindle Previewer 3 should have a 64-bit version: https://www.literatureandlatte.com/forum/viewtopic.php?p=284621#p284621

Maybe you can try that one? If that works, we would need to host it somewhere so the build can download it automatically like it does currently.

**Comment by slonopotamus** [comment]
See tdtds/kindlegen#36. It would be good if you also complained to KDP support that kindlegen download page doesn't offer a build for current MacOS version.

**Comment by mraible** [comment]
Based on [this Twitter poll](https://twitter.com/mraible/status/1338700754786217987), I think it might be easiest to drop MOBI. Most readers don't seem to use it.

Twitter poll

This poll isn't quite over, but I figured I'd embed a screenshot so you don't have to take it. 🙂

**Pull request closed without merging**
