### PR TITLE
resolves #184 add downloadable link

### LINKED ISSUE #184: Add ability to link to downloads
@Mogztter You sent me a prototype a while back that had a heading at the top that allowed you to link to the artifact downloads (e.g. PDF, EPUB). Do you think it'd be possible to add that to this template? 

I'd be happy to pay for your services to implement this feature.

### PR DESCRIPTION
**Pull request by ggrossetie**
image

resolves #184

### CODE REVIEW

**Comment by mraible** [comment]
Thank you, @ggrossetie!!

**Comment by mraible** [comment]
@ggrossetie Can you please trigger a new build to deploy this to https://infoq-mini-book.netlify.app/?

**Comment by mraible** [comment]
Do you know how to transfer the site? I'm not familiar with the process.

**Comment by ggrossetie** [comment]
> Do you know how to transfer the site? I'm not familiar with the process.

@mraible I think the easiest way is to create a new Netlify site from this repository. Once this is done, I will rename/remove my site so you can (re)use the subdomain `infoq-mini-book`.

**Comment by mraible** [comment]
@ggrossetie Can you rename your site so I can try to use `infoq-mini-book`?

**Comment by ggrossetie** [comment]
@mraible Done!

**Comment by mraible** [comment]
Thanks, @ggrossetie. I have successfully renamed wonderful-raindrop-7e92c2 to https://infoq-mini-book.netlify.app. 🤗

**Pull request merged**
